version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - db
    networks:
      - app_network
      - db_network  # Backend can talk to both frontend and database

  db:
    image: alpine
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - sqlite_data:/app/data
    networks:
      - db_network  # Database is isolated from frontend

volumes:
  sqlite_data:

networks:
  app_network:
    driver: bridge  # Standard Docker network type
  db_network:
    driver: bridge